version: '3'
volumes:
  bundle:
services:
  db:
    image: postgres:9.6
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start
    image: blog:dev
    volumes:
      - .:/app
      - bundle:/box
    depends_on:
      - db
    ports:
      - "3000:3000"
  bundle:
    image: busybox
    volumes:
      - bundle:/box

